name: Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome first-time issue authors
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const isFirstIssue = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: issue.user.login,
              state: 'all'
            }).then(res => res.data.length === 1);

            if (isFirstIssue) {
              const message = `👋 Welcome to rad.io, @${issue.user.login}! 

Thank you for opening your first issue. We appreciate you taking the time to contribute.

**What happens next?**
- A maintainer will review your issue and respond within a few days
- If this is a bug, we may ask for additional information
- If this is a feature request, we'll discuss it with the community

**Getting involved:**
- Check out our [Contributing Guide](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/CONTRIBUTING.md)
- Browse [good first issues](https://github.com/${context.repo.owner}/${context.repo.repo}/labels/good%20first%20issue) if you'd like to contribute
- Join discussions in [GitHub Discussions](https://github.com/${context.repo.owner}/${context.repo.repo}/discussions)

We're excited to have you in the community! 🎉`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: message
              });
            }

      - name: Welcome first-time PR authors
        if: github.event_name == 'pull_request_target'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const pulls = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: pr.user.login,
              state: 'all'
            });
            
            const isFirstPR = pulls.data.length === 1;

            if (isFirstPR) {
              const message = `🎉 Congratulations on your first PR, @${pr.user.login}! 

Thank you for contributing to rad.io! This is an exciting milestone.

**First-time contributor checklist:**
- [ ] I've read the [Contributing Guide](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/CONTRIBUTING.md)
- [ ] All tests pass locally (\`npm test\`)
- [ ] Code is linted (\`npm run lint\`)
- [ ] I've added myself to [CONTRIBUTORS.md](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/CONTRIBUTORS.md)

**What happens next?**
- Automated checks will run (tests, linting, type-checking)
- A maintainer will review your changes
- We may request changes or ask questions
- Once approved, your PR will be merged! 🚀

**Need help?**
- Comment on this PR with questions
- Check the [First-Time Contributor Checklist](https://github.com/${context.repo.owner}/${context.repo.repo}/blob/main/.github/FIRST_TIME_CONTRIBUTOR_CHECKLIST.md)
- Join [GitHub Discussions](https://github.com/${context.repo.owner}/${context.repo.repo}/discussions)

We're here to help and excited to see your contribution! Welcome to the rad.io community! 🎉`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: message
              });
            }
